# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reach_to_dendrogram <- function(reachability, pl_order) {
    .Call('dbscan_reach_to_dendrogram', PACKAGE = 'dbscan', reachability, pl_order)
}

dendrogram_to_reach <- function(x) {
    .Call('dbscan_dendrogram_to_reach', PACKAGE = 'dbscan', x)
}

dbscan_int <- function(data, eps, minPts, weights, borderPoints, type, bucketSize, splitRule, approx, frNN) {
    .Call('dbscan_dbscan_int', PACKAGE = 'dbscan', data, eps, minPts, weights, borderPoints, type, bucketSize, splitRule, approx, frNN)
}

dbscan_density_int <- function(data, eps, type, bucketSize, splitRule, approx) {
    .Call('dbscan_dbscan_density_int', PACKAGE = 'dbscan', data, eps, type, bucketSize, splitRule, approx)
}

frNN_int <- function(data, eps, type, bucketSize, splitRule, approx) {
    .Call('dbscan_frNN_int', PACKAGE = 'dbscan', data, eps, type, bucketSize, splitRule, approx)
}

JP_int <- function(nn, kt) {
    .Call('dbscan_JP_int', PACKAGE = 'dbscan', nn, kt)
}

SNN_sim_int <- function(nn) {
    .Call('dbscan_SNN_sim_int', PACKAGE = 'dbscan', nn)
}

kNN_int <- function(data, k, type, bucketSize, splitRule, approx) {
    .Call('dbscan_kNN_int', PACKAGE = 'dbscan', data, k, type, bucketSize, splitRule, approx)
}

optics_int <- function(data, eps, minPts, type, bucketSize, splitRule, approx, frNN) {
    .Call('dbscan_optics_int', PACKAGE = 'dbscan', data, eps, minPts, type, bucketSize, splitRule, approx, frNN)
}

